#################################################################
# Build Stage
#################################################################
FROM python:3.9-slim AS builder

# Working directory set karna
WORKDIR /app

# Copy only dependency file first for efficient caching
COPY requirements.txt .

# Install dependencies in a custom directory
RUN pip install --no-cache-dir -r requirements.txt --target=/app/deps

# Copy full application source code
COPY . .

#################################################################
# Final Distroless Runtime Stage
#################################################################
FROM gcr.io/distroless/python3-debian11

# Working directory set karna (each stage independent hota hai)
WORKDIR /app

# Copy dependencies and source code from builder stage
COPY --from=builder /app/deps /app/deps
COPY --from=builder /app .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app/deps"

# Expose the application port
EXPOSE 80

# Command to run the application
CMD ["run.py"]
